[build]
  command = "echo 'Building static website'"
  publish = "."

[build.environment]
  NODE_VERSION = "16"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  command = "echo 'Building deploy preview'"

[context.deploy-preview.environment]
  NODE_ENV = "preview"
